baseURL = 'https://luojiahai.com/'
languageCode = 'en-us'
title = 'luojiahai'
theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'luojiahai'                     # twitter.com/YOUR_TWITTER_ID
  github = 'luojiahai'                      # github.com/YOUR_GITHUB_ID
  instagram = 'luojiahai'                   # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'luojiahai'                    # linkedin.com/in/YOUR_LINKEDIN_ID
  threads = '@luojiahai'                    # threads.net/@YOUR_THREADS_ID

  # home page profile
  avatar = 'ljiahai@hotmail.com'            # gravatar email or image url
  name = 'luojiahai'
  bio = 'Hello, World!'

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = 'favicon.ico'                   # customize the default favicon
  appleTouchIcon = 'apple-touch-icon.png'   # customize the default Apple touch icon
