name: ci

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: install dependencies
        run: pnpm install
      - name: build with vitepress
        run: pnpm build
